apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
  - flux2-podmonitor.yaml
configMapGenerator:
- name: grafana-dashboards
  files:
    - dashboards/flux-control-plane.json
    - dashboards/flux-cluster.json
  options:
      labels:
        grafana_dashboard: "1"